# Generated by Django 4.2.7 on 2023-11-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Аккаунт в телеграмме"
                    ),
                ),
                (
                    "phonenumber",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "pd_contract",
                    models.FileField(
                        upload_to="", verbose_name="Договор об использовании ПД"
                    ),
                ),
                (
                    "storage_unit",
                    models.CharField(max_length=20, verbose_name="Склад хранения"),
                ),
                ("box_type", models.CharField(max_length=20, verbose_name="Вид бокса")),
                (
                    "lease_start_date",
                    models.DateTimeField(verbose_name="Дата начала аренды"),
                ),
                (
                    "lease_end_date",
                    models.DateTimeField(verbose_name="Дата окончания аренды"),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="Belongings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Cписок вещей"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belongings",
                        to="bot.user",
                        verbose_name="Кому принадлежат вещи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вещи",
            },
        ),
    ]
