# Generated by Django 4.2.7 on 2023-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_user_box_type_alter_user_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='box_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Вид бокса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lease_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания аренды'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lease_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала аренды'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pd_contract',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Договор об использовании ПД'),
        ),
        migrations.AlterField(
            model_name='user',
            name='storage_unit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Склад хранения'),
        ),
    ]
