# Generated by Django 4.2.7 on 2023-11-17 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_alter_user_box_type_alter_user_lease_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Хранилище",
                "verbose_name_plural": "Адрес хранилища",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="box_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="storage_unit",
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.PositiveSmallIntegerField(verbose_name="Размер бокса")),
                ("is_occupied", models.BooleanField(default=False)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box",
                        to="bot.storage",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "current_renter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rented_boxes",
                        to="bot.user",
                        verbose_name="Текущий арендатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бокс",
            },
        ),
        migrations.AddField(
            model_name="belongings",
            name="box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="belongings",
                to="bot.box",
                verbose_name="Бокс",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rented_box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renters",
                to="bot.box",
                verbose_name="Арендованный бокс",
            ),
        ),
    ]
