# Generated by Django 4.2.7 on 2023-11-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_storage_remove_user_box_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Бокс', 'verbose_name_plural': 'Боксы'},
        ),
    ]
